config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  root to: 'questions#index'

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get 'search', action: :search, controller: 'sphinx_search'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
        # get :all_users, on: :collection
      end

      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create update destroy], shallow: true
      end
    end
  end

  namespace :users do
    get '/set_email', to: 'emails#new'
    post '/set_email', to: 'emails#create'
  end

  resources :attachments, only: [:destroy]
  resources :links, only: [:destroy]

  concern :vote do
    member do
      put :vote_up
      put :vote_down
      delete :vote_cancel
    end
  end

  concern :commented do
    member do
      post :create_comment
    end
  end

  resources :questions, concerns: %i[vote commented] do
    resources :subscriptions, only: %i[create destroy], shallow: true
    resources :answers, only: %i[create edit update destroy], concerns: %i[vote commented], shallow: true do
      post :best_answer, on: :member
    end
  end

  resources :users, only: :show_rewards do
    get :show_rewards, on: :member
  end

  mount ActionCable.server => '/cable'
end

app/views/shared/_attachments.html.slim
- if resource.files.attached?
  - resource.files.each do |file|
    p id="attachment_#{file.id}"
      = link_to file.filename.to_s, url_for(file), target: '_blank'
      |  |
      - if can?(:destroy, file.record)
        = link_to 'Delete file', attachment_path(file), method: :delete, remote: true, class: 'btn btn-danger'

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected:"
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_flash_message.html.slim
main.container.mt-3
  div
    - flash.each do |key, msg|
      |  <div class="alert alert-
      = class_for_flash_message(key)
      |  ">
      = msg.html_safe

app/views/shared/_nav.html.slim
.container
  ul.nav.justify-content-end.mt-3
    = form_with url: search_path, local: true, method: :get do |f|
      .d-flex
        = f.text_field :search_body, class: 'form-control'
        = f.select :type, SphinxSearchService::TYPES , class: 'form-control'
        = f.submit 'Search', class: 'btn btn-primary'
    - if user_signed_in?
      li.nav-item
        = link_to 'Home', root_path, class: 'nav-link active'
      li.nav-item
        = link_to 'My Rewards', show_rewards_user_path(current_user), class: 'nav-link active'
      li.nav-item
        a.nav-link.active
          |  Welcome,
          b
            = current_user.email
      li.nav-item
        = link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link active'
    - else
      li.nav-item
        = link_to 'Sign up', new_user_registration_path, class: 'nav-link active'
      li.nav-item
        = link_to 'Log in', user_session_path, class: 'nav-link active'

app/views/shared/_vote.html.slim
.vote
  .rating id="rating-#{resource.class.name.underscore}-#{resource.id}"
    = "Rating: #{resource.rating}"

  - if user_signed_in? && !current_user.author?(resource)
    .vote-actions
      = link_to 'Up', polymorphic_path(resource, action: :vote_up),
              method: :put,
              data: { type: :json },
              remote: true, class: 'btn btn-primary btn-sm'
      = link_to 'Down',
              polymorphic_path(resource, action: :vote_down),
              method: :put,
              data: { type: :json },
              remote: true, class: 'btn btn-danger btn-sm mx-1'
      = link_to 'Cancel',
              polymorphic_path(resource, action: :vote_cancel),
              method: :delete,
              data: { type: :json },
              remote: true, class: 'btn btn-secondary btn-sm'