config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  root to: 'questions#index'

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get 'search', action: :search, controller: 'sphinx_search'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
        # get :all_users, on: :collection
      end

      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show create update destroy], shallow: true
      end
    end
  end

  namespace :users do
    get '/set_email', to: 'emails#new'
    post '/set_email', to: 'emails#create'
  end

  resources :attachments, only: [:destroy]
  resources :links, only: [:destroy]

  concern :vote do
    member do
      put :vote_up
      put :vote_down
      delete :vote_cancel
    end
  end

  concern :commented do
    member do
      post :create_comment
    end
  end

  resources :questions, concerns: %i[vote commented] do
    resources :subscriptions, only: %i[create destroy], shallow: true
    resources :answers, only: %i[create edit update destroy], concerns: %i[vote commented], shallow: true do
      post :best_answer, on: :member
    end
  end

  resources :users, only: :show_rewards do
    get :show_rewards, on: :member
  end

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :user

  has_many :links, dependent: :destroy, as: :linkable

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  has_many_attached :files

  validates :title, :body, :question_id, presence: true

  after_commit :send_notification, on: :create

  def send_notification
    NotifyAboutNewAnswerJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  include Voted
  include Commented

  before_action :authenticate_user!, except: %i[create edit update]
  before_action :set_question, only: %i[create]
  before_action :set_answer, only: %i[edit update destroy best_answer]
  after_action :publish_answer, only: [:create]

  authorize_resource

  def create
    @answer = @question.answers.build(answer_params)
    @answer.user = current_user
    flash.now[:notice] = 'Answer successfully created' if @answer.save
    # respond_to do |format|
    #   if @answer.save
    #     format.json { render json: @answer }
    #   else
    #     format.json { render json: @answer.errors.full_messages, status: :unprocessable_entity }
    #   end
    # end
  end

  def edit; end

  def update
    @answer.update(answer_params)
    @question = @answer.question
  end

  def destroy
    # return unless current_user&.author?(@answer)
    @answer.delete
    @question = @answer.question
    flash.now[:notice] = 'Your answer successfully deleted'
  end

  def best_answer
    @question = @answer.question
    # return unless current_user&.author?(@question)
    @question.set_best_answer(@answer)

    @best_answer = @question.best_answer
    @other_answers = @question.answers.where.not(id: @question.best_answer_id)
  end

  private

  def answer_params
    params.require(:answer).permit(:title, :body, files: [],
                                                  links_attributes: %i[name url _destroy id])
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    # @answer = @question.answers.find(params[:id])
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast("answers/#{params[:question_id]}",
                                 ApplicationController.render(
                                   partial: 'answers/answer_channel',
                                   locals: { question: @answer.question, answer: @answer, current_user: current_user }
                                 ))
  end
end

app/controllers/api/v1/answers_controller.rb
# frozen_string_literal: true

class Api::V1::AnswersController < Api::V1::BaseController
  before_action :set_question, only: %i[index create]
  before_action :set_answer, only: %i[show update destroy]

  def index
    @question = Question.includes(:answers)
    render json: @question
  end

  def show
    render json: @answer, serializer: AnswerWithAssociationSerializer
  end

  def create
    @answer = @question.answers.create(answer_params)
    @answer.user = current_resource_owner

    if @answer.save
      render json: @answer, status: :created
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  def update
    authorize! :update, @answer

    if @answer.update(answer_params)
      render json: @answer, status: :accepted
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    authorize! :destroy, @answer

    @answer.destroy
    render json: { messages: ['Your answer successfully deleted'] }
  end

  private

  def answer_params
    params.require(:answer).permit(:title, :body)
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
end

app/views/answers/_answer.html.slim
- cache answer do
  div id="answer-#{answer.id}"
    = render 'shared/flash_message'
    p= answer.title
    p= answer.body
    = render 'links/links_collection', resource: answer

    -if answer.files.attached?
      |  File:
      = render 'shared/attachments', resource: answer

    = render 'shared/vote', resource: answer

    .answer-comments id="answer-comments-#{answer.id}"
      h4 Comments:
      = render answer.comments
      - if current_user
        = render 'comments/form_answer', answer: answer

    - if can?(:best_answer, answer)
      p= link_to 'Best answer', best_answer_answer_path(answer), method: :post, remote: true

    - if can?(:update, answer)
      p= link_to 'Edit answer', '#', class: 'edit-answer-link', data: {answer_id: answer.id}
    - if can?(:destroy, answer)
      p= link_to 'Delete answer', answer_path(answer), method: :delete, remote: true
    - if can?(:update, answer)
      = form_with model: answer, class: 'hidden', html: {id: "edit-answer-#{answer.id}"}, local: false do |f|
        p
        = f.label :title
        = f.text_field :title, class: 'form-control'
        p
        = f.label :body
        = f.text_area :body, class: 'form-control'
        p
        = f.label :files
        = f.file_field :files, class: 'form-control', multiple: true, direct_upload: true
        p
        p
        = render 'links/link', resource: answer, f: f
        = f.submit 'Save'

app/views/answers/_answer_channel.html.slim
div id="answer-#{answer.id}"
  p= answer.title
  p= answer.body

  .answer-comments id="answer-comments-#{answer.id}"
    h4 Comments:
    = render answer.comments

app/views/answers/_best_answer.html.slim
/ p= link_to 'remove Best answer!', best_answer_answer_path(resource), method: :post, remote: true

- if resource&.persisted?
  h1 The best answer
  p= resource.title
  p= resource.body
  p= render 'shared/vote', resource: resource

- if can?(:update, resource)
  p= link_to 'Edit answer', '#', class: 'edit-answer-link', data: { answer_id: resource.id }
- if can? :destroy, resource
  p= link_to 'Delete answer', answer_path(resource), method: :delete, remote: true

- if can?(:update, resource)
  = form_with model: resource, class: 'hidden', html: { id: "edit-answer-#{resource.id}" }, local: false do |f|
    = f.label :title
    = f.text_area :title, class: 'form-control'
    = f.label :body
    = f.text_area :body, class: 'form-control'
    = f.label :files
    = f.file_field :files, class: 'form-control', multiple: true, direct_upload: true
    = render 'links/link', resource: resource , f: f
    = f.submit 'Save'

hr

app/views/answers/best_answer.js.erb
<%# if @best_answer %>
  $('.answers').html('<%= j render 'answers/best_answer', resource: @best_answer %>');
  $('.answers').append('<%= j render @other_answers %>');
<%# else %>
  // $('.answers').html('<%#= j render @question.answers %>');
<%# end %>

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  $('.new-answer #answer_title').val('');
  $('.new-answer #answer_body').val('');
  // $('.notice').text('<%= flash[:notice] %>');
  $('.new_name').val('');
  $('.new_url').val('');
  $('.nested-fields').remove();
<% end %>

app/views/answers/create_comment.js.erb
<% if @comment.persisted? %>
  $('.form-answer-comment #comment_body').val('');
<% end %>

app/views/answers/destroy.js.erb
$('.notice').text('<%= flash[:notice] %>')
$('.answers').html('<%= j render @question.answers %>');

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.errors.empty? %>
  <% if @question.best_answer.present?%>
    $('.answers').html('<%= j render 'answers/best_answer', resource: @question.best_answer %>');
    $('.answers').append('<%= j render @question.answers %>');
  <% else %>
    $('.answers').html('<%= j render @question.answers %>');
  <% end %>
<% end %>

<%# unless @answer.errors.present? %>
//  $('.answers').html('<%#= j render 'answers/best_answer', resource: @question.best_answer %>');
//  $('.answers').append('<%#= j render @question.answers %>');
<%# end %>